#!/usr/bin/env python3
"""Build the reviewed executable module from the pinned upstream reference.

The upstream project is distributed as a Markdown Skill with self-contained
Python blocks. This builder keeps definitions and required module state while
discarding the tutorial's live examples and print statements.
"""

from __future__ import annotations

import ast
import argparse
from pathlib import Path


SKILL_DIR = Path(__file__).resolve().parents[1]
REFERENCE = SKILL_DIR / "references" / "upstream-skill-v3.5.1.md"
OUTPUT = Path(__file__).resolve().parent / "a_stock_data" / "upstream_full.py"

REQUIRED_ASSIGNMENTS = {
    "_TDX_SERVERS",
    "SH_INDEX",
    "UA",
    "DATACENTER_URL",
    "EM_SESSION",
    "EM_MIN_INTERVAL",
    "_em_last_call",
    "REPORT_API",
    "PDF_TPL",
    "IWENCAI_BASE",
    "IWENCAI_KEY",
    "HSGT_HEADERS",
    "_BOARD_FS",
    "_BOARD_PERIOD",
    "_CNINFO_ORGID_MAP",
    "ZTB_UT",
    "SINA_OPT_HDR",
    "EM_HOT_BODY",
    "_ctx",
}

LOCAL_OVERLAYS = {
    "from mootdx.quotes import Quotes": (
        "try:\n"
        "    from mootdx.quotes import Quotes\n"
        "except ModuleNotFoundError:\n"
        "    Quotes = None"
    ),
    "import pandas as pd": (
        "try:\n"
        "    import pandas as pd\n"
        "except ModuleNotFoundError:\n"
        "    pd = None"
    ),
    'result = d.get("Result", {})\n    md = result.get("newMarketData", {})': (
        'result = d.get("Result") or {}\n'
        '    if isinstance(result, list):\n'
        '        result = result[0] if result and isinstance(result[0], dict) else {}\n'
        '    md = result.get("newMarketData", {})'
    ),
    'rows = md.get("marketData", "").split(";")': (
        'rows = [row for row in md.get("marketData", "").split(";") if row]'
    ),
    """for kwargs in ({'bestip': True}, {}):                   # fallback: bestip 测速 / 裸 factory
        try:
            c = Quotes.factory(market=market, **kwargs)
            if _validate(c, market):
                return c
        except Exception:
            continue""": (
        """config_path = Path.home() / ".mootdx" / "config.json"
    if config_path.exists():
        for kwargs in ({'bestip': True}, {}):
            try:
                c = Quotes.factory(market=market, **kwargs)
                if _validate(c, market):
                    return c
            except Exception:
                continue"""
    ),
}


def python_blocks(markdown: str) -> str:
    lines: list[str] = []
    active = False
    for line in markdown.splitlines():
        if line.startswith("```python"):
            active = True
            continue
        if active and line.startswith("```"):
            active = False
            lines.append("")
            continue
        if active:
            lines.append(line)
    return "\n".join(lines) + "\n"


def assigned_name(node: ast.Assign | ast.AnnAssign) -> str | None:
    targets = node.targets if isinstance(node, ast.Assign) else [node.target]
    if len(targets) != 1:
        return None
    target = targets[0]
    if isinstance(target, ast.Name):
        return target.id
    if isinstance(target, ast.Attribute) and isinstance(target.value, ast.Name):
        return target.value.id
    return None


def keep_node(node: ast.AST, source: str) -> bool:
    if isinstance(node, (ast.Import, ast.ImportFrom, ast.FunctionDef, ast.ClassDef)):
        return True
    if isinstance(node, (ast.Assign, ast.AnnAssign)):
        return assigned_name(node) in REQUIRED_ASSIGNMENTS
    if isinstance(node, ast.Expr):
        text = ast.get_source_segment(source, node) or ""
        return text.startswith("EM_SESSION.headers.update")
    if isinstance(node, ast.Try):
        text = ast.get_source_segment(source, node) or ""
        return "HTTPAdapter" in text and "EM_SESSION.mount" in text
    return False


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    source = python_blocks(REFERENCE.read_text(encoding="utf-8"))
    tree = ast.parse(source)
    segments = [
        ast.get_source_segment(source, node)
        for node in tree.body
        if keep_node(node, source)
    ]
    body = "\n\n".join(segment for segment in segments if segment)
    for original, replacement in LOCAL_OVERLAYS.items():
        if original not in body:
            raise RuntimeError(f"reviewed upstream overlay no longer matches: {original!r}")
        body = body.replace(original, replacement, 1)
    generated = (
        '"""Generated from the pinned a-stock-data v3.5.1 reference.\n\n'
        "Do not edit this file by hand. Run build_upstream_module.py after "
        "reviewing a reference update.\n"
        '"""\n\n'
        "from __future__ import annotations\n\n"
        f"{body}\n"
    )
    compile(generated, str(OUTPUT), "exec")
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != generated:
            print(f"generated module is stale: {OUTPUT}")
            return 1
        print(f"generated module is current: {OUTPUT}")
        return 0
    OUTPUT.write_text(generated, encoding="utf-8")
    print(f"generated {OUTPUT} ({generated.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
